### ISSUE TITLE
Expose wait method from Selenium

### ISSUE THREAD

**Issue by RobinBurgess** [jfinkhaeuser/unobtainium#14]
Currently only driver and config are exposed.
It would be good to be able to use the wait without having to require selenium.

**Comment by jfinkhaeuser** [comment]
Relates to #13, there doesn't appear to be such a thing.

If you can post a snippet on how to use the wait method without unobtainium, then re-open this issue and I can add this easily.

In the meantime, check out https://github.com/jfinkhaeuser/unobtainium-multiwait
