### ISSUE TITLE
Extend config syntax with an include mechanism

### ISSUE THREAD

**Issue by jfinkhaeuser** [jfinkhaeuser/unobtainium#6]
For projects configuring many different drivers, it may make sense to split the configuration conceptually into two parts: one that provides driver configurations, and one that provides other configuration values (which may include the driver to use by default).

Neither YAML nor JSON support including files. The config parser could be extended to interpret an 'include' key, e.g.

```yaml
---
include:
 - some_file.yml
 - some_other_file.json
```

vs.

```json
{
  "include": ["some_file.yml", "some_other_file.json"]
}
```

(Yes, we could mix configuration file languages)

**Comment by jfinkhaeuser** [comment]
@GContaldi Like that?

**Comment by GContaldi** [comment]
looks cool 👍
